login:
  oauth2_wechat_enabled:
    default: false
    client: true
  oauth2_wechat_client_id: ''
  oauth2_wechat_client_secret: ''
  oauth2_wechat_authorize_url: ''
    oauth2_wechat_authorize_signup_url: ''
  oauth2_wechat_token_url: ''
  oauth2_wechat_token_url_method:
    default: 'POST'
    type: enum
    choices:
      - GET
      - POST
  oauth2_wechat_callback_user_id_path: ''
  oauth2_wechat_callback_user_info_paths:
    type: list
    default: 'id'
  oauth2_wechat_fetch_user_details:
    default: true
    validator: "Oauth2FetchUserDetailsValidator"
  oauth2_wechat_user_json_url: ''
  oauth2_wechat_user_json_url_method:
    default: 'GET'
    type: enum
    choices:
      - GET
      - POST
  oauth2_wechat_json_user_id_path: ''
  oauth2_wechat_json_username_path: ''
  oauth2_wechat_json_name_path: ''
  oauth2_wechat_json_email_path: ''
  oauth2_wechat_json_email_verified_path: ''
  oauth2_wechat_json_avatar_path: ''
  oauth2_wechat_email_verified: false
  oauth2_wechat_overrides_email: false
  oauth2_wechat_send_auth_header: true
  oauth2_wechat_send_auth_body: true
  oauth2_wechat_debug_auth: false
  oauth2_wechat_authorize_options:
    default: 'scope'
    type: list
  oauth2_wechat_scope: ''
  oauth2_wechat_button_title:
    default: 'with OAuth2'
    client: true
  oauth2_wechat_allow_association_change:
    default: false
  oauth2_wechat_disable_csrf:
    default: false
    hidden: true
